import { CirclePlus } from 'lucide-react'

export const AcademicRankModalFormConfig = {
  moduleTitle: 'Manage Academic Ranks',
  title: 'Create Academic Rank',
  description: 'Provide the academic rank details below. Academic ranks are used for faculty positions (e.g., Instructor, Assistant Professor).',
  addButton: {
    id: 'add-academic-rank',
    label: 'Add Academic Rank',
    className: 'bg-primary text-primary-foreground rounded-lg px-4 py-2 hover:bg-primary/90 cursor-pointer',
    icon: CirclePlus,
    type: 'button',
    variant: 'default',
    permission: 'create-academic-rank',
  },
  fields: [
    {
      id: 'academic-rank-name',
      key: 'name',
      name: 'name',
      label: 'Rank Name',
      type: 'text',
      placeholder: 'e.g. Instructor I, Assistant Professor II',
      autocomplete: 'off',
      tabIndex: 1,
      required: true,
    },
    {
      id: 'academic-rank-code',
      key: 'code',
      name: 'code',
      label: 'Code',
      type: 'text',
      placeholder: 'e.g. INST-I, AP-II',
      autocomplete: 'off',
      tabIndex: 2,
    },
    {
      id: 'academic-rank-level',
      key: 'level',
      name: 'level',
      label: 'Level (1-100)',
      type: 'number',
      placeholder: 'e.g. 1, 2, 3...',
      autocomplete: 'off',
      tabIndex: 3,
      required: true,
      min: 1,
      max: 100,
    },
    {
      id: 'academic-rank-sort-order',
      key: 'sort_order',
      name: 'sort_order',
      label: 'Sort Order',
      type: 'number',
      placeholder: 'Display order (lower numbers first)',
      autocomplete: 'off',
      tabIndex: 4,
      min: 0,
    },
    {
      id: 'academic-rank-is-active',
      key: 'is_active',
      name: 'is_active',
      label: 'Active',
      type: 'checkbox',
      tabIndex: 5,
      defaultValue: true,
    },
    {
      id: 'academic-rank-description',
      key: 'description',
      name: 'description',
      label: 'Description',
      type: 'textarea',
      placeholder: 'Optional description for this academic rank',
      tabIndex: 6,
      rows: 3,
      className: 'rounded border p-2 w-full',
    },
  ],
  buttons: [
    {
      key: 'cancel',
      type: 'button',
      label: 'Cancel',
      variant: 'ghost',
      className: 'cursor-pointer',
    },
    {
      key: 'submit',
      type: 'submit',
      label: 'Save Academic Rank',
      variant: 'default',
      className: 'cursor-pointer',
    },
  ],
}
