import { CirclePlus } from 'lucide-react'

export const PositionModalFormConfig = {
  moduleTitle: 'Manage Positions',
  title: 'Create Position',
  description: 'Provide the position details below.',
  addButton: {
    id: 'add-position',
    label: 'Add Position',
    className: 'bg-primary text-primary-foreground rounded-lg px-4 py-2 hover:bg-primary/90 cursor-pointer',
    icon: CirclePlus,
    type: 'button',
    variant: 'default',
    permission: 'create-position',
  },
  fields: [
    {
      id: 'pos-code',
      key: 'pos_code',
      name: 'pos_code',
      label: 'Position Code',
      type: 'text',
      placeholder: 'e.g. PROF',
      autocomplete: 'off',
      tabIndex: 1,
    },
    {
      id: 'pos-name',
      key: 'pos_name',
      name: 'pos_name',
      label: 'Position Name',
      type: 'text',
      placeholder: 'Enter position name',
      autocomplete: 'off',
      tabIndex: 2,
    },
    {
      id: 'sector-id',
      key: 'sector_id',
      name: 'sector_id',
      label: 'Sector',
      type: 'single-select',
      placeholder: 'Select Sector (leave empty for system-wide)',
      options: [], // Will be populated dynamically
      tabIndex: 3,
      description: 'Leave empty for system-wide positions (e.g., President, VP)',
    },
    {
      id: 'authority-level',
      key: 'authority_level',
      name: 'authority_level',
      label: 'Authority Level (0-100)',
      type: 'number',
      placeholder: 'e.g. 50',
      min: 0,
      max: 100,
      tabIndex: 4,
      description: 'Higher number = more authority. Used for approval routing.',
    },
    {
      id: 'pos-description',
      key: 'description',
      name: 'description',
      label: 'Description',
      type: 'textarea',
      placeholder: 'Optional description',
      tabIndex: 5,
      rows: 3,
      className: 'rounded border p-2 w-full',
    },
  ],
  buttons: [
    {
      key: 'cancel',
      type: 'button',
      label: 'Cancel',
      variant: 'ghost',
      className: 'cursor-pointer',
    },
    {
      key: 'submit',
      type: 'submit',
      label: 'Save Position',
      variant: 'default',
      className: 'cursor-pointer',
    },
  ],
}

