import { CirclePlus } from 'lucide-react'

export const SectorModalFormConfig = {
  moduleTitle: 'Manage Sectors',
  title: 'Create Sector',
  description: 'Provide the sector details below. Sectors are top-level classifications (Academic, Administrative).',
  addButton: {
    id: 'add-sector',
    label: 'Add Sector',
    className: 'bg-primary text-primary-foreground rounded-lg px-4 py-2 hover:bg-primary/90 cursor-pointer',
    icon: CirclePlus,
    type: 'button',
    variant: 'default',
    permission: 'create-sector',
  },
  fields: [
    {
      id: 'sector-name',
      key: 'name',
      name: 'name',
      label: 'Sector Name',
      type: 'text',
      placeholder: 'e.g. Academic, Administrative',
      autocomplete: 'off',
      tabIndex: 1,
      required: true,
    },
    {
      id: 'sector-code',
      key: 'code',
      name: 'code',
      label: 'Sector Code',
      type: 'text',
      placeholder: 'e.g. ACAD, ADMIN',
      autocomplete: 'off',
      tabIndex: 2,
    },
    {
      id: 'sector-is-active',
      key: 'is_active',
      name: 'is_active',
      label: 'Active',
      type: 'checkbox',
      tabIndex: 3,
      defaultValue: true,
    },
    {
      id: 'sector-description',
      key: 'description',
      name: 'description',
      label: 'Description',
      type: 'textarea',
      placeholder: 'Optional description for this sector',
      tabIndex: 4,
      rows: 3,
      className: 'rounded border p-2 w-full',
    },
  ],
  buttons: [
    {
      key: 'cancel',
      type: 'button',
      label: 'Cancel',
      variant: 'ghost',
      className: 'cursor-pointer',
    },
    {
      key: 'submit',
      type: 'submit',
      label: 'Save Sector',
      variant: 'default',
      className: 'cursor-pointer',
    },
  ],
}
