import { CirclePlus } from 'lucide-react'

export const StaffGradeModalFormConfig = {
  moduleTitle: 'Manage Staff Grades',
  title: 'Create Staff Grade',
  description: 'Provide the staff grade details below. Staff grades are used for administrative positions (e.g., SG-1 to SG-33).',
  addButton: {
    id: 'add-staff-grade',
    label: 'Add Staff Grade',
    className: 'bg-primary text-primary-foreground rounded-lg px-4 py-2 hover:bg-primary/90 cursor-pointer',
    icon: CirclePlus,
    type: 'button',
    variant: 'default',
    permission: 'create-staff-grade',
  },
  fields: [
    {
      id: 'staff-grade-name',
      key: 'name',
      name: 'name',
      label: 'Grade Name',
      type: 'text',
      placeholder: 'e.g. Salary Grade 1, SG-15',
      autocomplete: 'off',
      tabIndex: 1,
      required: true,
    },
    {
      id: 'staff-grade-code',
      key: 'code',
      name: 'code',
      label: 'Code',
      type: 'text',
      placeholder: 'e.g. SG-1, SG-15',
      autocomplete: 'off',
      tabIndex: 2,
    },
    {
      id: 'staff-grade-level',
      key: 'level',
      name: 'level',
      label: 'Level (1-100)',
      type: 'number',
      placeholder: 'e.g. 1, 2, 3...',
      autocomplete: 'off',
      tabIndex: 3,
      required: true,
      min: 1,
      max: 100,
    },
    {
      id: 'staff-grade-sort-order',
      key: 'sort_order',
      name: 'sort_order',
      label: 'Sort Order',
      type: 'number',
      placeholder: 'Display order (lower numbers first)',
      autocomplete: 'off',
      tabIndex: 4,
      min: 0,
    },
    {
      id: 'staff-grade-is-active',
      key: 'is_active',
      name: 'is_active',
      label: 'Active',
      type: 'checkbox',
      tabIndex: 5,
      defaultValue: true,
    },
    {
      id: 'staff-grade-description',
      key: 'description',
      name: 'description',
      label: 'Description',
      type: 'textarea',
      placeholder: 'Optional description for this staff grade',
      tabIndex: 6,
      rows: 3,
      className: 'rounded border p-2 w-full',
    },
  ],
  buttons: [
    {
      key: 'cancel',
      type: 'button',
      label: 'Cancel',
      variant: 'ghost',
      className: 'cursor-pointer',
    },
    {
      key: 'submit',
      type: 'submit',
      label: 'Save Staff Grade',
      variant: 'default',
      className: 'cursor-pointer',
    },
  ],
}
